name: geektg
services:
  worker:
    public: true
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 1Gi
      memory: 2Gi
    volumes:
      - worker:/data
 
volumes:
  worker:
    size: 2Gi
